services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy
    ports:
      - "8080:8080"
      - "9901:9901"
      - "1234:1234"
    volumes:
      - ./docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml