services:
  redis:
    image: redis:6.2.5-alpine
    ports:
      - '6379:6379'
    command: --loglevel warning
    networks:
      - internal
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    ports:
      - '8080:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - internal
    command:
      - start-dev
      - --import-realm
      - --log-level=ERROR
    volumes:
      - ./docker/keycloak/realm.json:/opt/keycloak/data/import/realm.json

networks:
  internal:
