name: cicd

on:
  push:

jobs:
  outdated-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: proto outdated

  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: bun install
      - run: bun run sync
      - run: bun run build
        env:
          QUEUE_REDIS_HOST: redis

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: bun install
      - run: bun check
      - run: bun lint

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: bun install
      - run: bun format:check
        id: format_check
        continue-on-error: true
      - if: failure()
        run: echo "::warning Code style issues detected::${{join(steps.format_check.outputs.*, '\n')}}"

  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      keycloak:
        image: quay.io/keycloak/keycloak:22.0
        options: >-
          --health-cmd "curl -f http://localhost:8080/realms/master"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install xz-utils
        run: apt-get update && apt-get install xz-utils
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - run: bun install
      - run: bun run test
        env:
          QUEUE_REDIS_HOST: redis
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-result
          retention-days: 30
