name: cicd

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v1
      - run: bun install

      - run: bun run sync
      - run: bun run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun check
      - run: bun lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bunx playwright install --with-deps
      - run: bun run test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-result
          retention-days: 30
